"""Use TicketStatus enum

Revision ID: e3f69236c8f2
Revises: 718113471ea9
Create Date: 2026-01-11 18:26:48.729547

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3f69236c8f2"
down_revision: Union[str, Sequence[str], None] = "718113471ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    status_enum = sa.Enum(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="ticketstatus"
    )
    status_enum.create(op.get_bind())

    # Alter the column using a cast
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN status "
        "TYPE ticketstatus USING status::ticketstatus"
    )

    op.alter_column(
        "ticket",
        "status",
        existing_type=sa.VARCHAR(),
        type_=status_enum,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ticket",
        "status",
        existing_type=sa.Enum(
            "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="ticketstatus"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )

    # Drop the enum type
    op.execute("DROP TYPE ticketstatus")
    # ### end Alembic commands ###
